function Datacentre_rebuild()
%DATACENTRE_REBUILD  Auto-generated by slx2script from Datacentre.slx (chart "VirtualMachine").
%   Regenerated on 18-Jun-2026 23:49:59. Do not hand-edit; re-run slx2script instead.

    model = 'Datacentre_rebuilt';
    if bdIsLoaded(model), close_system(model, 0); end
    new_system(model);
    add_block('sflib/Chart', [model '/VirtualMachine']);
    chart = chartByPath([model '/VirtualMachine']);
    chart.ActionLanguage = 'MATLAB';

    % --- events ---
    e = Stateflow.Event(chart); e.Name = 'PowerOn'; e.Scope = 'Local';
    e = Stateflow.Event(chart); e.Name = 'PowerOff'; e.Scope = 'Local';
    e = Stateflow.Event(chart); e.Name = 'Suspend'; e.Scope = 'Local';
    e = Stateflow.Event(chart); e.Name = 'Resume'; e.Scope = 'Local';
    e = Stateflow.Event(chart); e.Name = 'Reset'; e.Scope = 'Local';

    % --- states ---
    s1 = Stateflow.State(chart); s1.LabelString = 'PoweredOff'; s1.Position = [60 60 150 60];
    s2 = Stateflow.State(chart); s2.LabelString = 'PoweringOn'; s2.Position = [340 60 150 60];
    s3 = Stateflow.State(chart); s3.LabelString = 'Resetting'; s3.Position = [620 60 150 60];
    s4 = Stateflow.State(chart); s4.LabelString = 'PoweringOff'; s4.Position = [60 220 150 60];
    s5 = Stateflow.State(chart); s5.LabelString = 'PoweredOn'; s5.Position = [340 220 150 60];
    s6 = Stateflow.State(chart); s6.LabelString = 'Suspending'; s6.Position = [620 220 150 60];
    s7 = Stateflow.State(chart); s7.LabelString = 'Resuming'; s7.Position = [340 380 150 60];
    s8 = Stateflow.State(chart); s8.LabelString = 'Suspended'; s8.Position = [620 380 150 60];

    % --- transitions ---
    t = Stateflow.Transition(chart);
    t.Destination = s1; t.DestinationOClock = 0;
    t.SourceEndpoint = [135 20]; t.MidPoint = [135 40];
    t = Stateflow.Transition(chart);
    t.Source = s4; t.Destination = s1;
    t = Stateflow.Transition(chart);
    t.Source = s3; t.Destination = s5;
    t = Stateflow.Transition(chart);
    t.Source = s1; t.Destination = s2;
    t.LabelString = 'PowerOn';
    t = Stateflow.Transition(chart);
    t.Source = s5; t.Destination = s3;
    t.LabelString = 'Reset';
    t = Stateflow.Transition(chart);
    t.Source = s2; t.Destination = s5;
    t = Stateflow.Transition(chart);
    t.Source = s5; t.Destination = s4;
    t.LabelString = 'PowerOff';
    t = Stateflow.Transition(chart);
    t.Source = s7; t.Destination = s5;
    t = Stateflow.Transition(chart);
    t.Source = s5; t.Destination = s6;
    t.LabelString = 'Suspend';
    t = Stateflow.Transition(chart);
    t.Source = s6; t.Destination = s8;
    t = Stateflow.Transition(chart);
    t.Source = s8; t.Destination = s7;
    t.LabelString = 'Resume';

    Simulink.BlockDiagram.arrangeSystem(model);
    fprintf('Rebuilt %s: %d states.\n', model, numel(chart.find('-isa','Stateflow.State')));
end

function ch = chartByPath(p)
    charts = find(sfroot, '-isa', 'Stateflow.Chart');
    ch = charts(arrayfun(@(c) strcmp(c.Path, p), charts));
    assert(isscalar(ch), 'Could not resolve chart at %s', p);
end
