function outFile = slx2script(modelFile, chartName, outFile)
%SLX2SCRIPT Reverse-engineer a Stateflow chart into a reconstruction script.
%
%   slx2script(MODELFILE, CHARTNAME, OUTFILE) introspects the named Stateflow
%   chart inside the Simulink model MODELFILE and writes a standalone MATLAB
%   function OUTFILE that rebuilds an equivalent chart from scratch using the
%   Stateflow programmatic API.
%
%   This demonstrates that the *structure* of a .slx can be recovered to a
%   model-construction .m file by introspection (find_system / sfroot / the
%   Stateflow object model). Geometry is preserved where it is read back;
%   GUIDs and auto-layout details are intentionally not reproduced.
%
%   Example:
%       slx2script('Datacentre.slx', 'VirtualMachine', 'Datacentre_rebuild.m')

    if nargin < 1 || isempty(modelFile), modelFile = 'Datacentre.slx'; end
    if nargin < 2 || isempty(chartName), chartName = 'VirtualMachine';  end
    if nargin < 3 || isempty(outFile),   outFile   = 'Datacentre_rebuild.m'; end

    [~, model] = fileparts(modelFile);
    wasLoaded  = bdIsLoaded(model);
    if ~wasLoaded, load_system(modelFile); end

    try
        chart = find(sfroot, '-isa', 'Stateflow.Chart', 'Name', chartName);
        assert(isscalar(chart), 'Expected one chart named "%s", found %d.', chartName, numel(chart));

        states      = chart.find('-isa', 'Stateflow.State');
        transitions = chart.find('-isa', 'Stateflow.Transition');
        events      = chart.find('-isa', 'Stateflow.Event');

        [~, fcnName] = fileparts(outFile);
        q = @(s) ['''' strrep(char(s), '''', '''''') ''''];   % MATLAB-quote a string

        fid = fopen(outFile, 'w');
        assert(fid > 0, 'Could not open %s for writing.', outFile);
        c = onCleanup(@() fclose(fid));

        wl = @(varargin) fprintf(fid, '%s\n', sprintf(varargin{:}));

        rebuiltModel = [model '_rebuilt'];

        % ---- header --------------------------------------------------------
        wl('function %s()', fcnName);
        wl('%%%s  Auto-generated by slx2script from %s (chart "%s").', upper(fcnName), modelFile, chartName);
        wl('%%   Regenerated on %s. Do not hand-edit; re-run slx2script instead.', datestr(now)); %#ok<TNOW1,DATST>
        wl('');
        wl('    model = %s;', q(rebuiltModel));
        wl('    if bdIsLoaded(model), close_system(model, 0); end');
        wl('    new_system(model);');
        wl('    add_block(''sflib/Chart'', [model ''/%s'']);', chartName);
        wl('    chart = chartByPath([model ''/%s'']);', chartName);
        wl('    chart.ActionLanguage = %s;', q(char(chart.ActionLanguage)));
        wl('');

        % ---- events --------------------------------------------------------
        if ~isempty(events)
            wl('    %% --- events ---');
            for k = 1:numel(events)
                wl('    e = Stateflow.Event(chart); e.Name = %s; e.Scope = %s;', ...
                    q(events(k).Name), q(char(events(k).Scope)));
            end
            wl('');
        end

        % ---- states --------------------------------------------------------
        % name -> generated variable, so transitions can refer back to them
        varOf = containers.Map('KeyType', 'char', 'ValueType', 'char');
        wl('    %% --- states ---');
        for k = 1:numel(states)
            v = sprintf('s%d', k);
            varOf(stateKey(states(k))) = v;
            wl('    %s = Stateflow.State(chart); %s.LabelString = %s; %s.Position = %s;', ...
                v, v, q(states(k).LabelString), v, mat2str(states(k).Position));
        end
        wl('');

        % ---- transitions ---------------------------------------------------
        wl('    %% --- transitions ---');
        for k = 1:numel(transitions)
            t = transitions(k);
            wl('    t = Stateflow.Transition(chart);');
            if isempty(t.Source)   % default transition (no source state)
                wl('    t.Destination = %s; t.DestinationOClock = %g;', ...
                    varOf(stateKey(t.Destination)), t.DestinationOClock);
                wl('    t.SourceEndpoint = %s; t.MidPoint = %s;', ...
                    mat2str(t.SourceEndpoint), mat2str(t.MidPoint));
            else
                wl('    t.Source = %s; t.Destination = %s;', ...
                    varOf(stateKey(t.Source)), varOf(stateKey(t.Destination)));
            end
            if ~isempty(char(t.LabelString))
                wl('    t.LabelString = %s;', q(t.LabelString));
            end
        end
        wl('');

        wl('    Simulink.BlockDiagram.arrangeSystem(model);');
        wl('    fprintf(''Rebuilt %%s: %%d states.\\n'', model, numel(chart.find(''-isa'',''Stateflow.State'')));');
        wl('end');
        wl('');

        % ---- local helper emitted into the generated file ------------------
        wl('function ch = chartByPath(p)');
        wl('    charts = find(sfroot, ''-isa'', ''Stateflow.Chart'');');
        wl('    ch = charts(arrayfun(@(c) strcmp(c.Path, p), charts));');
        wl('    assert(isscalar(ch), ''Could not resolve chart at %%s'', p);');
        wl('end');

        clear c;  % flush/close the file
        fprintf('Wrote %s  (%d states, %d transitions, %d events).\n', ...
            outFile, numel(states), numel(transitions), numel(events));
    catch ME
        if ~wasLoaded, close_system(model, 0); end
        rethrow(ME);
    end
    if ~wasLoaded, close_system(model, 0); end
end

function k = stateKey(obj)
%STATEKEY Stable identity for a state, used to map transition endpoints.
    k = sprintf('id%d', obj.Id);
end
